apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets-api-1
  title: Migrate Secrets API 2
  description: Copies the secrets from HCP Vault to AWS Secrets Manager
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        - repository
      properties:
        organization:
          title: Organization Name
          type: string
          description: |
            Github Organization where the repository is stored.
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a Dry Run to simulate a migration of secrets.
          type: boolean
          default: true

  steps:
  # Fetch defaultRead entities
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Fetch all Selected Entities in defaultRead
      input:
        organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}

  output:
    text:      
      - title: Migration Summary
        content: |
          ### Repository: ${{ parameters.repository }}
          Organization: ${{ parameters.organization }}
          ${{ parameters.dryRun }}
          Status: ${{ steps.call_migrate_endpoint.output.data.status }}
          Request ID: ${{ steps.call_migrate_endpoint.output.data.request_id }}
          HTTP Code: ${{ steps.call_migrate_endpoint.output.code }}

      - title: Migration Message
        content: ${{ steps.call_migrate_endpoint.output.data.message }}

      - title: Development Environment - Vault
        content: ${{ steps.call_migrate_endpoint.output.data.data.dev.vault_env }}

      - title: Development Environment - Secrets Found
        content: ${{ steps.call_migrate_endpoint.output.data.data.dev.secrets_found }}

      - title: Development Environment - Copied
        content: ${{ steps.call_migrate_endpoint.output.data.data.dev.copied }}

      - title: Development Environment - Error  
        content: ${{ steps.call_migrate_endpoint.output.data.data.dev.error }}

      - title: Staging Environment - Vault
        content: ${{ steps.call_migrate_endpoint.output.data.data.stag.vault_env }}

      - title: Staging Environment - Secrets Found
        content: ${{ steps.call_migrate_endpoint.output.data.data.stag.secrets_found }}

      - title: Staging Environment - Message
        content: ${{ steps.call_migrate_endpoint.output.data.data.stag.message || 'None' }}

      - title: Production Environment - Vault
        content: ${{ steps.call_migrate_endpoint.output.data.data.prod.vault_env }}

      - title: Production Environment - Secrets Found
        content: ${{ steps.call_migrate_endpoint.output.data.data.prod.secrets_found }}

      - title: Production Environment - Error
        content: ${{ steps.call_migrate_endpoint.output.data.data.prod.error || 'None' }}

      - title: Raw Output
        content: ${{ steps.call_migrate_endpoint.output | dump }}
