apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets-api-1
  title: Migrate Secrets API 2
  description: Copies the secrets from HCP Vault to AWS Secrets Manager
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        - repository
      properties:
        organization:
          title: Organization Name
          type: string
          description: |
            Github Organization where the repository is stored.
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a Dry Run to simulate a migration of secrets.
          type: boolean
          default: true

  steps:
  # Fetch defaultRead entities
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Fetch all Selected Entities in defaultRead
      input:
        organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}

  output:
    text:
      - title: Migration Summary
        content: |
          **Repository:** ${{ parameters.repository }}
          **Organization:** ${{ parameters.organization }}
          **Dry Run:** ${{ parameters.dryRun ? 'Yes' : 'No' }}
          **Status:** ${{ steps.call_migrate_endpoint.output.status }}
          **Request ID:** ${{ steps.call_migrate_endpoint.output.request_id }}

      - title: Migration Message
        content: |
          ${{ steps.call_migrate_endpoint.output.message }}

      - title: Environment Results
        content: |
          ## Development Environment
          **Vault Environment:** ${{ steps.call_migrate_endpoint.output.data.dev.vault_env }}
          **Secrets Found:** ${{ steps.call_migrate_endpoint.output.data.dev.secrets_found }}
          **Copied:** ${{ steps.call_migrate_endpoint.output.data.dev.copied ? 'Yes' : 'No' }}
          ${{ steps.call_migrate_endpoint.output.data.dev.error ? '**Error:** ' + steps.call_migrate_endpoint.output.data.dev.error : '' }}
          ${{ steps.call_migrate_endpoint.output.data.dev.secret_keys ? '**Secret Keys:** ' + steps.call_migrate_endpoint.output.data.dev.secret_keys.join(', ') : '' }}

          ## Staging Environment  
          **Vault Environment:** ${{ steps.call_migrate_endpoint.output.data.stag.vault_env }}
          **Secrets Found:** ${{ steps.call_migrate_endpoint.output.data.stag.secrets_found }}
          **Copied:** ${{ steps.call_migrate_endpoint.output.data.stag.copied ? 'Yes' : 'No' }}
          ${{ steps.call_migrate_endpoint.output.data.stag.error ? '**Error:** ' + steps.call_migrate_endpoint.output.data.stag.error : '' }}
          ${{ steps.call_migrate_endpoint.output.data.stag.message ? '**Message:** ' + steps.call_migrate_endpoint.output.data.stag.message : '' }}
          ${{ steps.call_migrate_endpoint.output.data.stag.secret_keys ? '**Secret Keys:** ' + steps.call_migrate_endpoint.output.data.stag.secret_keys.join(', ') : '' }}

          ## Production Environment
          **Vault Environment:** ${{ steps.call_migrate_endpoint.output.data.prod.vault_env }}  
          **Secrets Found:** ${{ steps.call_migrate_endpoint.output.data.prod.secrets_found }}
          **Copied:** ${{ steps.call_migrate_endpoint.output.data.prod.copied ? 'Yes' : 'No' }}
          ${{ steps.call_migrate_endpoint.output.data.prod.error ? '**Error:** ' + steps.call_migrate_endpoint.output.data.prod.error : '' }}
          ${{ steps.call_migrate_endpoint.output.data.prod.secret_keys ? '**Secret Keys:** ' + steps.call_migrate_endpoint.output.data.prod.secret_keys.join(', ') : '' }}

      - title: Secrets Summary Table
        content: |
          | Environment | Vault Env | Secrets Found | Copied | Status |
          |-------------|-----------|---------------|---------|--------|
          | Dev | ${{ steps.call_migrate_endpoint.output.data.dev.vault_env }} | ${{ steps.call_migrate_endpoint.output.data.dev.secrets_found }} | ${{ steps.call_migrate_endpoint.output.data.dev.copied ? 'Yes' : 'No' }} | ${{ steps.call_migrate_endpoint.output.data.dev.error ? '❌ Error' : '✅ OK' }} |
          | Staging | ${{ steps.call_migrate_endpoint.output.data.stag.vault_env }} | ${{ steps.call_migrate_endpoint.output.data.stag.secrets_found }} | ${{ steps.call_migrate_endpoint.output.data.stag.copied ? 'Yes' : 'No' }} | ${{ steps.call_migrate_endpoint.output.data.stag.error ? '❌ Error' : (steps.call_migrate_endpoint.output.data.stag.secrets_found > 0 ? '✅ OK' : '⚠️ No Secrets') }} |
          | Production | ${{ steps.call_migrate_endpoint.output.data.prod.vault_env }} | ${{ steps.call_migrate_endpoint.output.data.prod.secrets_found }} | ${{ steps.call_migrate_endpoint.output.data.prod.copied ? 'Yes' : 'No' }} | ${{ steps.call_migrate_endpoint.output.data.prod.error ? '❌ Error' : '✅ OK' }} |

      - title: Error Details
        content: |
          ${{ steps.call_migrate_endpoint.output.data.dev.error ? '**Dev Error:** ' + steps.call_migrate_endpoint.output.data.dev.error : '' }}
          
          ${{ steps.call_migrate_endpoint.output.data.stag.error ? '**Staging Error:** ' + steps.call_migrate_endpoint.output.data.stag.error : '' }}
          
          ${{ steps.call_migrate_endpoint.output.data.prod.error ? '**Production Error:** ' + steps.call_migrate_endpoint.output.data.prod.error : '' }}
          
          ${{ (!steps.call_migrate_endpoint.output.data.dev.error && !steps.call_migrate_endpoint.output.data.stag.error && !steps.call_migrate_endpoint.output.data.prod.error) ? 'No errors reported.' : '' }}

      - title: Complete Output (Debug)
        content: |
          ```json
          ${{ steps.call_migrate_endpoint.output | dump }}
          ```
