---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets
  title: Migrate Secrets from HCP Vault to AWS Secrets Manager
  description: Migrate secret keys and values from HCP Vault to AWS Secrets Manager across all environments
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        #- organization
        - repository
      properties:
        #organization:
        #  title: Organization Name
        #  type: string
        #  description: |
        #    Github Organization where the repository is stored.
        #  default: MoveRDC
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a dry run to preview what will be migrated.
          type: boolean
          default: true
        #skywayBaseUrl:
        #  title: Skyway Base URL. Only used by Skyway team for testing purposes
        #  type: string
        #  default: "http://sentinel.cicd-prod.moveaws.com"

  steps:
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Migrating secrets from Vault to AWS Secrets Manager
      input:
        #organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}
        #skywayBaseUrl: ${{ parameters.skywayBaseUrl }}

  output:
    text:
      - title: Migration Summary
        content: |
          ${{ steps.call_migrate_endpoint.output.migrationSummary }}

      - title: Raw Output
        content: ${{ steps.call_migrate_endpoint.output | dump }}
