apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets-api-1
  title: Migrate Secrets API 2
  description: Copies the secrets from HCP Vault to AWS Secrets Manager
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        - repository
      properties:
        organization:
          title: Organization Name
          type: string
          description: |
            Github Organization where the repository is stored.
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a Dry Run to simulate a migration of secrets.
          type: boolean
          default: true

  steps:
  # Fetch defaultRead entities
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Fetch all Selected Entities in defaultRead
      input:
        organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}

  output:
    text:      
      - title: Migration Summary
        content: |
          Repository: ${{ parameters.organization }} / ${{ parameters.repository }}
          
          Dry-run: ${{ parameters.dryRun }}
          
          Status: ${{ steps.call_migrate_endpoint.output.data.status }}
          
          ## ${{ steps.call_migrate_endpoint.output.data.message }}

          ### Env: ${{ steps.call_migrate_endpoint.output.data.data.dev.vault_env }}

          **Secrets found:** ${{ steps.call_migrate_endpoint.output.data.data.dev.secrets_found }}

          Secrets: ${{ steps.call_migrate_endpoint.output.data.data.dev.secret_keys }}

      - title: Raw Output
        content: ${{ steps.call_migrate_endpoint.output | dump }}
