apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets-api
  title: Migrate Secrets API
  description: Copies the secrets from HCP Vault to AWS Secrets Manager
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        - repository
      properties:
        organization:
          title: Organization Name
          type: string
          description: |
            Github Organization where the repository is stored.
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a Dry Run to simulate a migration of secrets.
          type: boolean
          default: true
        skywayBaseUrl:
          title: Specify the Skyway base URL you want to use.
          type: string

  steps:
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Migrating secrets from Vault to AWS Secrets Manager
      input:
        organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}
        skywayBaseUrl: ${{ parameters.skywayBaseUrl }}

  output:
    text:      
      - title: Migration Summary
        content: |
          ${{ steps.call_migrate_endpoint.output.table }}

      - title: Raw Output
        content: ${{ steps.call_migrate_endpoint.output | dump }}
