apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: migrate-secrets-api-1
  title: Migrate Secrets API 2
  description: Copies the secrets from HCP Vault to AWS Secrets Manager
  labels:
    realtor.com/version: 1.0.0
spec:
  owner: skyway
  type: service
  lifecycle: production
  system: skyway

  parameters:
    - title: Enter repository information
      description: |
        # Info
        Copies the values of a secret from Vault to AWS Secrets Manager.
      required:
        - repository
      properties:
        organization:
          title: Organization Name
          type: string
          description: |
            Github Organization where the repository is stored.
        repository:
          title: Repository Name
          type: string
          pattern: "^(?!.*moverdc/).*$"
          description: |
            Repository name of repository to be updated
            (Do not include MoveRDC/ in the name)
        dryRun:
          title: Perform a Dry Run to simulate a migration of secrets.
          type: boolean
          default: true

  steps:
  # Fetch defaultRead entities
    - id: call_migrate_endpoint
      action: skyway:migrate-endpoint
      name: Fetch all Selected Entities in defaultRead
      input:
        organization: ${{ parameters.organization }}
        repository: ${{ parameters.repository }}
        dryRun: ${{ parameters.dryRun }}

  output:
    text:
      - title: Migration Summary
        content: |
          Repository: ${{ parameters.repository }}
          Organization: ${{ parameters.organization }}
          Dry Run: ${{ parameters.dryRun ? 'Yes' : 'No' }}
          Status: ${{ steps.call_migrate_endpoint.output.data.status }}

      - title: Migration Message
        content: ${{ steps.call_migrate_endpoint.output.data.message }}

      - title: Development Environment
        content: |
          Vault Environment: ${{ steps.call_migrate_endpoint.output.data.dev.vault_env }}
          Secrets Found: ${{ steps.call_migrate_endpoint.output.data.dev.secrets_found }}
          Copied: ${{ steps.call_migrate_endpoint.output.data.dev.copied ? 'Yes' : 'No' }}
          Secret Keys: ${{ steps.call_migrate_endpoint.output.data.dev.secret_keys ? steps.call_migrate_endpoint.output.data.dev.secret_keys.join(', ') : 'None' }}
          Error: ${{ steps.call_migrate_endpoint.output.data.dev.error || 'None' }}

      - title: Staging Environment
        content: |
          Vault Environment: ${{ steps.call_migrate_endpoint.output.data.stag.vault_env }}
          Secrets Found: ${{ steps.call_migrate_endpoint.output.data.stag.secrets_found }}
          Copied: ${{ steps.call_migrate_endpoint.output.data.stag.copied ? 'Yes' : 'No' }}
          Message: ${{ steps.call_migrate_endpoint.output.data.stag.message || 'None' }}
          Secret Keys: ${{ steps.call_migrate_endpoint.output.data.stag.secret_keys ? steps.call_migrate_endpoint.output.data.stag.secret_keys.join(', ') : 'None' }}
          Error: ${{ steps.call_migrate_endpoint.output.data.stag.error || 'None' }}

      - title: Production Environment
        content: |
          Vault Environment: ${{ steps.call_migrate_endpoint.output.data.prod.vault_env }}
          Secrets Found: ${{ steps.call_migrate_endpoint.output.data.prod.secrets_found }}
          Copied: ${{ steps.call_migrate_endpoint.output.data.prod.copied ? 'Yes' : 'No' }}
          Secret Keys: ${{ steps.call_migrate_endpoint.output.data.prod.secret_keys ? steps.call_migrate_endpoint.output.data.prod.secret_keys.join(', ') : 'None' }}
          Error: ${{ steps.call_migrate_endpoint.output.data.prod.error || 'None' }}

      - title: Raw Output
        content: ${{ steps.call_migrate_endpoint.output | dump }}
